services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Distributor\SalesforceCase\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # registry update listeners
  DigitalMarketingFramework\Typo3\Distributor\SalesforceCase\Registry\EventListener\DistributorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Registry\Event\DistributorRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Distributor\SalesforceCase\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent
